name: CI/CD Pipeline

on:
  push:
    branches: [ create_github_actions ]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
          architecture: x64
      
      - name: Install Python Virtual Environment
        run: pip3 install virtualenv
      
      - name: Set up Virtual Environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
      
      - name: Activate and Install Dependencies into virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
      
      - name: Create Zipfile archive of Dependencies
        run: |
          cd ./venv/lib/python3.12/site-packages
          zip -r9 ../../../../api.zip .
      
      - name: Add App to Zip file
        run: cd ./src && zip -g ../api.zip -r .
      
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip